// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Projekt___moment_5
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Lånebelopp")]
            public float Lånebelopp { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"RenoveringAvBostad")]
            public float RenoveringAvBostad { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"LösenLån")]
            public float LösenLån { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"KöpAvBil")]
            public float KöpAvBil { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"ÖvrigKonsumtion")]
            public float ÖvrigKonsumtion { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Återbetalningstid")]
            public float Återbetalningstid { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"TillsvidareAnställning")]
            public float TillsvidareAnställning { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Egenföretagare")]
            public float Egenföretagare { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Pensionär")]
            public float Pensionär { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Arbetssökande")]
            public float Arbetssökande { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"CivilståndGift")]
            public float CivilståndGift { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"CivilståndSambo")]
            public float CivilståndSambo { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"CivilståndEnsamstående")]
            public float CivilståndEnsamstående { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Medsökande")]
            public float Medsökande { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Barn20årEllerYngre")]
            public float Barn20årEllerYngre { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"Villa")]
            public float Villa { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Bostadsrätt")]
            public float Bostadsrätt { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Hyresrätt")]
            public float Hyresrätt { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"Betalningsanmärkningar")]
            public float Betalningsanmärkningar { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"AndraLån")]
            public float AndraLån { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"IsApproved")]
            public float IsApproved { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Lånebelopp")]
            public float Lånebelopp { get; set; }

            [ColumnName(@"RenoveringAvBostad")]
            public float RenoveringAvBostad { get; set; }

            [ColumnName(@"LösenLån")]
            public float LösenLån { get; set; }

            [ColumnName(@"KöpAvBil")]
            public float KöpAvBil { get; set; }

            [ColumnName(@"ÖvrigKonsumtion")]
            public float ÖvrigKonsumtion { get; set; }

            [ColumnName(@"Återbetalningstid")]
            public float Återbetalningstid { get; set; }

            [ColumnName(@"TillsvidareAnställning")]
            public float TillsvidareAnställning { get; set; }

            [ColumnName(@"Egenföretagare")]
            public float Egenföretagare { get; set; }

            [ColumnName(@"Pensionär")]
            public float Pensionär { get; set; }

            [ColumnName(@"Arbetssökande")]
            public float Arbetssökande { get; set; }

            [ColumnName(@"CivilståndGift")]
            public float CivilståndGift { get; set; }

            [ColumnName(@"CivilståndSambo")]
            public float CivilståndSambo { get; set; }

            [ColumnName(@"CivilståndEnsamstående")]
            public float CivilståndEnsamstående { get; set; }

            [ColumnName(@"Medsökande")]
            public float Medsökande { get; set; }

            [ColumnName(@"Barn20årEllerYngre")]
            public float Barn20årEllerYngre { get; set; }

            [ColumnName(@"Villa")]
            public float Villa { get; set; }

            [ColumnName(@"Bostadsrätt")]
            public float Bostadsrätt { get; set; }

            [ColumnName(@"Hyresrätt")]
            public float Hyresrätt { get; set; }

            [ColumnName(@"Betalningsanmärkningar")]
            public float Betalningsanmärkningar { get; set; }

            [ColumnName(@"AndraLån")]
            public float AndraLån { get; set; }

            [ColumnName(@"IsApproved")]
            public uint IsApproved { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("IsApproved");
            if (labelColumn == null)
            {
                throw new Exception("IsApproved column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
